openapi: 3.0.0
info:
  version: '0.9.0'
  title: Science Data Storage Service REST Endpoints
  description: >-
    The Science Data Storage Service is an HTTP service that allows science data to be added 
    to the Science Data Storage System.  There are two Data Storage Services, 
    the Summit Data Storage Service (SDSS) with inserts items into the Summit Storage, 
    and the HQ Data Storage Service (HQDSS), which inserts items into the TIO Archive.

    Visit [TIO Website](http://www.tmt.org) for more information.

    Complete codebase is available on [Github](https://github.com/tmtsoftware/dms).
  x-logo:
    url: tmt.png
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  '/ancillary/program/{programId}':
    post:
      tags:
        - Science Data Storage Service
      description: "Add one ancillary file associated with a program to the Science Archive"
      summary: Add science ancillary file to program
      operationId: addScienceAncillaryFileProgram
      parameters:
        - $ref: "../shared.yml#/components/parameters/programIdPath"
        - name: topic
          in: query
          required: true
          description: "Type of file (e.g. weather map, PSFR data)"
          example: "WeatherMap"
          schema:
            type: string
      requestBody:
        description: file to be uploaded
        required: true
        content:
          application/octet-stream:
            schema: {}
      responses:
        '201':
          description: The submitted file is successfully added. A description of the added file including its fileId is returned as JSON.
          content:
            application/json:
              schema:
                $ref: "../shared.yml#/components/schemas/AncillaryFileProgramResponse"
              example:
                uri: tio:hq/2039B-042_top-end-temps-20450412.fits
                timestamp: 2045-04-12T23:20:50.52Z
                programId: 2039B-042
                fileName: 2039B-042_top-end-temps-20450412.fits
                fileId: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        '401':
          description:
            "Bad Request. The caller is not authorized for this operation."
        '500':
          description:
            "Bad Request. Arguments provided were not correct or were incomplete: with explanatory text."
  '/ancillary/observation/{observationId}':
    post:
      tags:
        - Science Data Storage Service
      description: "Add one ancillary file associated with an observation to the Science Archive"
      summary: Add science ancillary file to observation
      operationId: addScienceAncillaryFileObservation
      parameters:
        - $ref: "../shared.yml#/components/parameters/observationIdPath"
        - name: topic
          in: query
          required: true
          description: "Type of file (e.g. weather map, PSFR data)"
          example: "WeatherMap"
          schema:
            type: string
      requestBody:
        description: file to be uploaded
        required: true
        content:
          application/octet-stream:
            schema: {}
      responses:
        '201':
          description: The submitted file is successfully added. A description of the added file including its fileId is returned as JSON.
          content:
            application/json:
              schema:
                $ref: "../shared.yml#/components/schemas/AncillaryFileObservationResponse"
              example:
                uri: tio:hq/2039B-042-123_top-end-temps-20450412.fits
                timestamp: 2045-04-12T23:20:50.52Z
                observationId: 2039B-042-123
                fileName: 2039B-042-123_top-end-temps-20450412.fits
                fileId: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        '401':
          description:
            "Bad Request. The caller is not authorized for this operation."
        '500':
          description:
            "Bad Request. Arguments provided were not correct or were incomplete: with explanatory text."
  '/ancillary/exposure/{exposureId}':
    post:
      tags:
        - Science Data Storage Service
      description: "Add one ancillary file associated with an exposure to the Science Archive"
      summary: Add science ancillary file to exposure
      operationId: addScienceAncillaryFileExposure
      parameters:
        - $ref: "../shared.yml#/components/parameters/exposureId"
        - name: topic
          in: query
          required: true
          description: "Type of file (e.g. weather map, PSFR data)"
          example: "WeatherMap"
          schema:
            type: string
      requestBody:
        description: file to be uploaded
        required: true
        content:
          application/octet-stream:
            schema: {}
      responses:
        '201':
          description: The submitted file is successfully added. A description of the added file including its fileId is returned as JSON.
          content:
            application/json:
              schema:
                $ref: "../shared.yml#/components/schemas/AncillaryFileExposureResponse"
              example:
                uri: tio:hq/2039B-042-123-IRIS-IMG-SCI1-1234_top-end-temps-20450412.fits
                timestamp: 2045-04-12T23:20:50.52Z
                exposureId: 2039B-042-123-IRIS-IMG-SCI1-1234
                fileName: 2039B-042-123-IRIS-IMG-SCI1-1234_top-end-temps-20450412.fits
                fileId: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        '401':
          description:
            "Bad Request. The caller is not authorized for this operation."
        '500':
          description:
            "Bad Request. Arguments provided were not correct or were incomplete: with explanatory text."
  '/ancillary/night/{night}':
    post:
      tags:
        - Science Data Storage Service
      description: "Add one ancillary file associated with a night to the Science Archive"
      summary: Add science ancillary file to night
      operationId: addScienceAncillaryFileNight
      parameters:
        - name: night
          in: path
          required: true
          description: "This is an UTC date to associate the file to in YYYYMMDD."
          example: 20250412
          schema:
            type: string
        - name: topic
          in: query
          required: true
          description: "Type of file (e.g. weather map, PSFR data)"
          example: "WeatherMap"
          schema:
            type: string
      requestBody:
        description: file to be uploaded
        required: true
        content:
          application/octet-stream:
            schema: {}
      responses:
        '201':
          description: The submitted file is successfully added. A description of the added file including its fileId is returned as JSON.
          content:
            application/json:
              schema:
                $ref: "../shared.yml#/components/schemas/AncillaryFileProgramResponse"
              example:
                uri: tio:hq/2039B-042_top-end-temps-20450412.fits
                timestamp: 2045-04-12T23:20:50.52Z
                programId: 2039B-042
                fileName: 2039B-042_top-end-temps-20450412.fits
                fileId: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        '401':
          description:
            "Bad Request. The caller is not authorized for this operation."
        '500':
          description:
            "Bad Request. Arguments provided were not correct or were incomplete: with explanatory text."
  '/prepareNewFile':
    get:
      description: "Prepare Summit system for a new image to be written to the Summit Storage.  When this endpoint 
      is called, The Summit Data Storage Service assigns an internal filename and constructs a URI for the file, and
      creates a new entry in the Dataset Information Database with this mapping.   
      
      The internal filename is in the format UTCDATE-XXXXX where UTCDATE  is the current UTC date in YYYYMMDD 
      format, and XXXXX is a running number managed by SDSS, reset to 0 at the start of each UTC day.
      
      This endpoint is also used by the Detector Data Collection Service to obtain a path to copy a file from 
      the transfer location to a long-term storage space.  This endpoint is only available at the Summit.
      
      These operations are also performed for other endpoints in the service.  This endpoint is intended for use 
      solely by the DDCS when it copies files to the storage directly."
      summary: Prepare storage for a new file
      tags:
        - Science Data Storage Service
      operationId: prepare for new file
      responses:
        '200':
          description: "A JSON structure with the path of the file in Summit Storage and the URI file handle."
          content:
            application/json:
              schema:
                type: object
                properties:
                  path:
                    type: string
                    description: ""
                  uri:
                    type: string
                    format: uri
                    description: "Handle for file used to download file"
              example:
                path: /data/science/20450314_28342.fits
                uri: tio:summit/20450314_28342.fits
        '400':
          description:
            "Bad Request. Arguments provided were not correct or were incomplete: with explanatory text provided."