openapi: 3.0.0
info:
  version: '0.1-SNAPSHOT'
  title: Engineering Database Access Service API
  description: >-
      The Engineering Access Service (EAS) is an HTTP service that provides querying capability to retrieve sets of engineering data (both event and non-event data) from the Engineering Database.

      Visit [TMT Website](http://www.tmt.org) for more information.

      Complete codebase is available on [Github](https://github.com/tmtsoftware/dms).

      Collection of routes listed on this page are http end points exposed by TMT common software.
  x-logo:
    url: tmt.png
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

paths:

  '/eng/events': 
    get:
      description: Returns values for a set of event parameters over a specified time range
      summary: Get engineering data
      tags:
        - Engineering Access Service
      operationId: retrieve data
      parameters:
        - $ref: '../shared.yml#/components/parameters/startDateReq'
        - $ref: '../shared.yml#/components/parameters/startTimeReq'
        - $ref: '../shared.yml#/components/parameters/endDateReq'
        - $ref: '../shared.yml#/components/parameters/endTimeReq'
        - name: timeStep
          in: query
          description: period of data returned in seconds, resampled using method defined in `resampleMethod` parameter.
          schema:
            type: integer
            minimum: 1
        - name: resampleMethod
          in: query
          schema:
            $ref: '../shared.yml#/components/schemas/ResampleMethod'
          description: >
            Resampling methods if `timeStep` is specified:
              * `interp` - linearly interpolated between data points
              * `nearest` - nearest matched time to a past or future event
              * `past` - nearest past time
              * `binned` - data is binned
        - name: subsystem
          in: query
          description: specify subsystem to retrieve all events for a subsystem
          schema:
            $ref: '../shared.yml#/components/schemas/Subsystem'
        - name: events
          in: query
          description: list of Events to get data for
          schema: 
            type: array
            items:
              $ref: '../shared.yml#/components/schemas/EventKey'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../shared.yml#/components/schemas/EngData'
        '404':
          description: Not Found
  '/eng/logs':
    get:
      description: >-
        Returns log messages over a specified time range
      summary: Get system logs
      tags:
        - Engineering Access Service
      operationId: retrieve logs
      parameters:
        - $ref: '../shared.yml#/components/parameters/startDateReq'
        - $ref: '../shared.yml#/components/parameters/startTimeReq'
        - $ref: '../shared.yml#/components/parameters/endDateReq'
        - $ref: '../shared.yml#/components/parameters/endTimeReq'
        - name: subsystem
          in: query
          required: true
          schema: 
            type: array
            items:
              $ref: '../shared.yml#/components/schemas/Subsystem'
        - name: component
          in: query
          required: true
          schema: 
            type: array
            items:
              type: string
        - name: outputType
          in: query
          schema:
            type: string
            enum: [json, text]
            default: json
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../shared.yml#/components/schemas/LogData'
            text/plain:
              schema:
                $ref: '../shared.yml#/components/schemas/SimpleLogData'
        '404':
          description: Not Found
  '/eng/files/search':
    get:
      description: >-
        Returns a list of URIs for engineering ancillary data that match query parameters
      summary: Find engineering ancillary data
      tags:
        - Engineering Access Service
      operationId: search files
      parameters:
        - $ref: '../shared.yml#/components/parameters/startDateReq'
        - $ref: '../shared.yml#/components/parameters/startTimeReq'
        - $ref: '../shared.yml#/components/parameters/endDateReq'
        - $ref: '../shared.yml#/components/parameters/endTimeReq'
        - name: subsystem
          in: query
          required: true
          description: specify subsystem to retrieve all events for a subsystem
          schema:
            $ref: '../shared.yml#/components/schemas/Subsystem'
        - name: channelName
          in: query
          required: true
          schema:
            type: string
        - name: tags
          in: query
          schema:
            type: array
            items:
             $ref: '../shared.yml#/components/schemas/Tag'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../shared.yml#/components/schemas/FileData'
        '404':
          description: Not Found
  '/eng/files':
    get:
      description: Get one or more ancillary files based on URI. If more than one file is specified, exposures will be returned in a zip file.
      summary: Get engineering ancillary file(s)
      tags: 
      - Engineering Access Service
      operationId: retrieve eng ancillary files
      parameters:
      - name: URIs
        in: query
        description: One or more URIs of ancillary files to retrieve 
        required: true
        schema: 
          type: array
          items: 
            type: string
      - name: package
        in: query
        description: Type of packaging if multiple files are requested
        schema:
          $ref: '../shared.yml#/components/schemas/PackageType'
      responses:
        '200':
          description: OK
          content:
            application/octet-stream:
              schema: {}
        '404':
          description: Not Found
  '/eng/all/{subsystem}':
    get:
      description: >-
        Returns all engineering data for a subsystem over a specified time range
      summary: Get all engineering data for a subsystem
      tags:
        - Engineering Access Service
      operationId: retrieve all
      parameters:
        - $ref: '../shared.yml#/components/parameters/startDateReq'
        - $ref: '../shared.yml#/components/parameters/startTimeReq'
        - $ref: '../shared.yml#/components/parameters/endDateReq'
        - $ref: '../shared.yml#/components/parameters/endTimeReq'
        - name: subsystem
          in: path
          required: true
          description: specify subsystem to retrieve all events for a subsystem
          schema:
            $ref: '../shared.yml#/components/schemas/Subsystem'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../shared.yml#/components/schemas/AnyData'
        '404':
          description: Not Found
