openapi: 3.0.0
info:
  version: '0.9.0'
  title: Calibration Data Service Endpoints
  description: >-
    The Calibration Data Service (CDS) is an HTTP service that identifies and returns the location of calibration files suitable for reduction.

    Visit [TIO Website](https://www.tmt.org) for more information.

    Complete codebase is available on [Github](https://github.com/tmtsoftware/dms).
  x-logo:
    url: tmt.png
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

paths:
  '/calibration/search':
    get:
      description: Search storage for calibration files based on query parameters
      summary: Search storage
      tags:
      - Calibration Data Service
      operationId: locate calibration files
      parameters:
        - $ref: '../shared.yml#/components/parameters/originalFilename'
        - $ref: '../shared.yml#/components/parameters/calibrationType'
        - $ref: '../shared.yml#/components/parameters/startTime'
        - $ref: '../shared.yml#/components/parameters/endTime'
        - $ref: '../shared.yml#/components/parameters/instrument'
        - $ref: '../shared.yml#/components/parameters/channel'
        - $ref: '../shared.yml#/components/parameters/integrationTime'
        - $ref: '../shared.yml#/components/parameters/coadds'
        - $ref: '../shared.yml#/components/parameters/filter'
        - $ref: '../shared.yml#/components/parameters/scale'
        - $ref: '../shared.yml#/components/parameters/spectralResolution'
        - $ref: '../shared.yml#/components/parameters/aoMode'
      responses:
        '200':
          description: Exposure IDs of matching files
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '../shared.yml#/components/schemas/ExposureId'
        '404':
          description: Not Found
  '/calibration/exposure/{exposureId}':
    get:
      description: >-
        Search storage for the best calibration file of a specific type for a given exposure.
        The best calibration is determined using an algorithm specific to the file type requested
        based on the metadata in the exposure identified by the exposureId.
      summary: Search storage for calibration based on exposure
      tags:
        - Calibration Data Service
      operationId: locate calibration for exposure
      parameters:
        - name: exposureId
          in: query
          required: true
          schema:
            $ref: '../shared.yml#/components/schemas/ExposureId'
        - $ref: '../shared.yml#/components/parameters/calibrationTypeReq'
      responses:
        '200':
          description: Exposure ID of matching file
          content:
            application/json:
              schema:
                $ref: '../shared.yml#/components/schemas/ExposureId'
        '404':
          description: Not Found
