openapi: 3.0.0
info:
  version: '0.9'
  title: Engineering Database File Access Service API
  description: >-
    The Engineering File Access API is HTTP endpoints for discovering ancillary files in the Engineering
    Database and for retrieving files from the Engineering Database.
    <p>
    The complete DMS codebase is available on [Github](https://github.com/tmtsoftware/dms).
    <p>
    The collection of routes listed on this page are HTTP endpoints exposed by TMT Common Software.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: 'https://future_eng_file_server/V1'
tags:
  - name: Discovery Endpoints
    description: Endpoints for file queries about engineering files in the Engineering Database.
  - name: Retrieval Endpoints
    description: Endpoints for retrieving an engineering file from the Engineering Database.
externalDocs:
  description: "References for time format"
  url: https://datatracker.ietf.org/doc/html/rfc3339
paths:
  '/eng/files/search':
    get:
      tags:
        - Discovery Endpoints
      description: >-
        Returns a list of file information on engineering ancillary files that match query parameters. Information
        includes a link to each document and a *fileId* that can also be used for retrieval. 
        Results can be returned as JSON (default) or as an IVOA VOTable. In both cases, the information is the same.
      summary: Discover ancillary files in the Engineering Database
      operationId: searchFiles
      externalDocs:
        description: "Reference for IVOA VOTable"
        url: https://www.ivoa.net/documents/VOTable/
      parameters:
        - $ref: "../eng-shared/eng-shared.yaml#/components/parameters/startTime"
        - $ref: "../eng-shared/eng-shared.yaml#/components/parameters/endTime"
        - name: subsystem
          in: query
          required: true
          description: Specify a subsystem to use to create a unique topic key with the channelName. 
                 An example topic is APS.apsChannel
          example: APS
          schema:
            $ref: '../eng-shared/eng-shared.yaml#/components/schemas/Subsystem'
        - name: channelName
          in: query
          required: true
          example: apsChannel
          description: Specify a channelName to use to create a unique topic key with the provided subsystem.
            An example topic is APS.apsChannel
          schema:
            type: string
        - name: resultType
          in: query
          description: The user can request the format of the query result as JSON or an IVOA VOTable
          schema:
            type: string
            default: JSON
            enum:
              - JSON
              - VOTABLE
        - name: tags
          in: query
          style: form
          explode: false
          required: false
          schema:
            type: array
            description: Tags can be provided to further filter results of the time-based query.
              Note that tags and their values must be provided when submitting a file and tags must
              be defined in the subsystem data specification document. Tag values are defined in tagValues
              and values must be in the same order as the tags.
            items:
              type: string
          example:
            [location, camera]
        - name: tagValues
          in: query
          style: form
          explode: false
          required: false
          schema:
            type: array
            description: Tags can be provided to further filter results of the time-based query.
              Note that tags and their values must be provided when submitting a file and tags must
              be defined in the subsystem data specification document. Tag values are defined in tagValues
              and values must be in the same order as the tags.
            items:
              type: string
            example:
             [top-end, blue]

      responses:
        '200':
          description: The response for a successful discovery query is a fileItem object
          content:
            application/json:
              schema:
                $ref: '../eng-shared/eng-shared.yaml#/components/schemas/FileData'
        '400':
          description:
            "Bad Request. Arguments provided were not correct or were incomplete: with explanatory text provided."
        '404':
          description: "No files were found using these parameters."
  /eng/file/{fileId}:
    get:
      tags:
        - Retrieval Endpoints
      description: Retrieve a single ancillary file.
      summary: Retrieve a single engineering ancillary file from the Engineering Database
      operationId: retrieveEngAncillaryFile
      parameters:
        - in: path
          name: fileId
          description: FileId of a previously stored ancillary files for retrieval
          required: true
          schema:
            type: string
            example: a1c6a2ab-4b01-4253-b4c9-70e04b3b48fc
      responses:
        '200':
          description: File is located and returned successfully.
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
              example:
                "opaque file returned"
        '400':
          description:
            "Bad Request. Arguments provided were not correct or were incomplete: with explanatory text."
        '404':
          description: "No files was found with provied fileid."
  /eng/files:
    get:
      tags:
        - Retrieval Endpoints
      description:
        Get one or more ancillary files based on one or more fileIds.
        Files will be returned in a compressed collection in the format specified by the optional package parameter.
        The default package value is zip.
        <p>
        If any of the fileIds cannot be associated with a file, the entire request is rejected.
      summary: Retrieve one or more engineering ancillary files from the Engineering Database
      operationId: retrieveEngAncillaryFiles
      parameters:
      - name: fileIds
        in: query
        description: One or more fileIds of previously stored ancillary files for retrieval.
        required: true
        style: form
        explode: false
        example: a1c6a2ab-4b01-4253-b4c9-70e04b3b48fc, a1c6a2ab-4b01-4253-b4c9-70e04b3b53af
        schema:
          type: array
          minItems: 1
          items:
            type: string
      - name: package
        in: query
        description: The type of packaging used when returning the collection of requested files.
        schema:
          $ref: '../eng-shared/eng-shared.yaml#/components/schemas/PackageType'
      responses:
        '200':
          description: All files located and returned successfully in a compressed file. The name of the file
            is generated by the service.
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
              example: resultFiles2065.gzip
        '400':
          description:
              "Bad Request. Arguments provided were not correct or were incomplete: with explanatory text."
        '404':
          description: One or more of the files were not found.

  /eng/all/{subsystem}:
     get:
      tags:
        - Retrieval Endpoints
      description: >-
        Retrieve all engineering files for a subsystem over a specified time range.
        <p>
        Files will be returned in a compressed collection in the format specified by the optional package parameter.
        The default package value is zip.
      summary: Retrieve all engineering files for a subsystem over a specified time range
      operationId: retrieveSubsystemAll
      parameters:
        - $ref: "../eng-shared/eng-shared.yaml#/components/parameters/startTime"
        - $ref: "../eng-shared/eng-shared.yaml#/components/parameters/endTime"
        - name: subsystem
          in: path
          required: true
          description: Specify a subsystem to be used to capture all engineering data.
          example: APS
          schema:
            $ref: '../eng-shared/eng-shared.yaml#/components/schemas/Subsystem'
        - name: package
          in: query
          description: The type of packaging used when returning the set of requested files.
          schema:
            $ref: '../eng-shared/eng-shared.yaml#/components/schemas/PackageType'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../eng-shared/eng-shared.yaml#/components/schemas/FileData'
        '404':
          description: Not Found
