openapi: 3.0.0
info:
  version: '0.9'
  title: Engineering Database File Access Service API
  description: >-
    The Engineering File Access API is HTTP endpoints for discovering and retrieving ancillary files previously 
    stored in the Engineering Database.
    <p>
    The complete DMS codebase is available on [Github](https://github.com/tmtsoftware/dms).
    <p>
    The collection of routes listed on this page are HTTP endpoints exposed by TIO Common Software.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: 'https://future_eng_file_server/V1'
tags:
  - name: Discovery Endpoints
    description: Endpoints for file queries about engineering files in the Engineering Database.
  - name: Retrieval Endpoints
    description: Endpoints for retrieving an engineering file from the Engineering Database.
  - name: Admin Endpoints
    description: Endpoints for operating on the store of ancillary files.
externalDocs:
  description: "References for time format"
  url: https://datatracker.ietf.org/doc/html/rfc3339
paths:
  '/eng/files/search/{subsystem}/{channel}':
    get:
      tags:
        - Discovery Endpoints
      description: >-
        Returns a list of file information for engineering ancillary files that match query parameters. Information
        includes a link to each document and a *fileId* that can also be used for retrieval. 
        Results can be returned as JSON (default) or as an IVOA VOTable. In both cases, the information is the same.
      summary: Discover ancillary files in the Engineering Database
      operationId: searchFiles
      parameters:
        - $ref: "../eng-shared/eng-shared.yaml#/components/parameters/subsystem"
        - $ref: "../eng-shared/eng-shared.yaml#/components/parameters/channel"
        - $ref: "../eng-shared/eng-shared.yaml#/components/parameters/startTime"
        - $ref: "../eng-shared/eng-shared.yaml#/components/parameters/endTime"
        - $ref: "../eng-shared/eng-shared.yaml#/components/parameters/resultType"
        - $ref: "../eng-shared/eng-shared.yaml#/components/parameters/tagName"
        - $ref: "../eng-shared/eng-shared.yaml#/components/parameters/tagValue"
      responses:
        '200':
          description: The response for a successful discovery query is a list fileItem object
          content:
            application/json:
              schema:
                $ref: '../eng-shared/eng-shared.yaml#/components/schemas/FileData'
        '400':
          description:
            "Bad Request. Arguments provided were not correct or were incomplete: with explanatory text provided."
        '404':
          description: "No files were found using these parameters."

  '/eng/files/since':
    get:
      tags:
        - Discovery Endpoints
      description: >-
        Returns a list of file information on engineering ancillary files that have been added since the
        provided timestamp.
        Results can be returned as JSON (default) or as an IVOA VOTable. In both cases, the information is the same.
      summary: Discover ancillary files in the Engineering Database created since a specific timestamp
      operationId: sinceFiles
      externalDocs:
        description: "Reference for IVOA VOTable"
        url: https://www.ivoa.net/documents/VOTable/
      parameters:
        - name: sinceTime
          in: query
          required: true
          description: sinceTime is the time that should be used to look for new files in RFC 3339 format.
          example: 2025-04-12T23:20:50.52Z
          schema:
            type: string
            format: date-time
        - $ref: "../eng-shared/eng-shared.yaml#/components/parameters/resultType"
      responses:
        '200':
          description: The response for a successful discovery query is a list fileItem object
          content:
            application/json:
              schema:
                $ref: '../eng-shared/eng-shared.yaml#/components/schemas/FileData'
        '400':
          description:
            "Bad Request. Arguments provided were not correct or were incomplete: with explanatory text provided."
        '404':
          description: "No files were found using these parameters."
  /eng/file:
    get:
      tags:
        - Retrieval Endpoints
      description: Retrieve a single ancillary file using its unique URI.
      summary: Retrieve a single engineering ancillary file from the Engineering Database
      operationId: retrieveEngAncillaryFileByURI
      parameters:
        - $ref: "../eng-shared/eng-shared.yaml#/components/parameters/uri"
      responses:
        '200':
          description: File is located and returned successfully.
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
              example:
                "opaque file returned"
        '400':
          description:
            "Bad Request. Arguments provided were not correct or were incomplete: with explanatory text."
        '404':
          description: "No file was found with the provided URI."
    delete:
      tags:
        - Admin Endpoints
      description: Delete a single ancillary file.
      summary: Remove a single engineering ancillary file from the Engineering Database. Caution!
      operationId: deleteEngAncillaryFile
      parameters:
        - $ref: "../eng-shared/eng-shared.yaml#/components/parameters/uri"
      responses:
        '200':
          description: File is returned and deleted from the store.
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
              example:
                "opaque deleted file returned"
        '400':
          description:
            "Bad Request. Arguments provided were not correct or were incomplete: with explanatory text."
        '404':
          description: "No file was found with the provided URI."
  /eng/files:
    get:
      tags:
        - Retrieval Endpoints
      description:
        Get one or more ancillary files based on one or more URIs.
        Files will be returned in a compressed collection in the format specified by the optional package parameter.
        The default package value is gzip.
        <p>
        If any of the URIs cannot be associated with a file, the entire request is rejected.
      summary: Retrieve one or more engineering ancillary files from the Engineering Database
      operationId: retrieveEngAncillaryFiles
      parameters:
      - name: uri
        in: query
        description: One or more URIs of previously stored ancillary files for retrieval.
        required: true
        style: form
        explode: false
        example: [tio:hq/topEndTemps-2025-04-12T23:20:50.52Z, tio:hq/topEndTemps-2025-04-13T23:20:00.32Z]
        schema:
          type: array
          minItems: 1
          items:
            type: string
      - $ref: "../eng-shared/eng-shared.yaml#/components/parameters/package"
      responses:
        '200':
          description: All files located and returned successfully in a compressed file. The name of the file
            is generated by the service.
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
              example: resultFiles2065.gzip
        '400':
          description:
              "Bad Request. Arguments provided were not correct or were incomplete: with explanatory text."
        '404':
          description: One or more of the files were not found.

  /eng/all/{subsystem}:
     get:
      tags:
        - Retrieval Endpoints
      description: >-
        Retrieve all engineering files for a subsystem over a specified time range.
        <p>
        Files will be returned in a compressed collection in the format specified by the optional package parameter.
        The default package value is gzip.
      summary: Retrieve all engineering files for a subsystem over a specified time range
      operationId: retrieveSubsystemAll
      parameters:
        - $ref: "../eng-shared/eng-shared.yaml#/components/parameters/startTime"
        - $ref: "../eng-shared/eng-shared.yaml#/components/parameters/endTime"
        - $ref: "../eng-shared/eng-shared.yaml#/components/parameters/subsystem"
        - $ref: "../eng-shared/eng-shared.yaml#/components/parameters/package"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../eng-shared/eng-shared.yaml#/components/schemas/FileData'
        '404':
          description: Not Found
