openapi: 3.0.0
info:
  version: '1.0'
  title: Science Data Access Service REST Endpoints
  description: >-
    The Science Data Access Service (SDAS) is an HTTP service that allows science data to be retrieved from the Science Data Storage System.

    Visit [TMT Website](http://www.tmt.org) for more information.

    Complete codebase is available on [Github](https://github.com/tmtsoftware/dms).

    Collection of routes listed on this page are http end points exposed by TMT common software.
  x-logo:
    url: tmt.png
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
   
  '/science/retrieve/{URI}':
    get:
      description: Download one or more exposures based on URI
      summary: Get science file(s)
      tags: 
      - Science Data Access Service
      operationId: retrieve science files
      parameters:
      - name: URI
        in: path
        description: location of files
        required: true
        schema: 
          type: array
          items:
            type: string
      - name: compression
        in: query
        description: Type of compression, if desired
        schema:
          $ref: '#/components/schemas/CompressionType'
      - name: package
        in: query
        description: Type of packaging, if multiple files are downloaded
        schema:
          $ref: '#/components/schemas/PackageType'
      responses:
        '200':
          description: OK
          content:
            application/octet-stream:
              schema: {}
        '404':
          description: Not Found
  '/science/files':
    get:
      description: Locate an exposure based on Exposure ID. 
      summary: Locate science file
      tags: 
      - Science Data Access Service
      operationId: locate science file
      parameters:
      - name: exposureId
        in: query
        description: Exposure ID of exposure 
        required: true
        schema: 
          $ref: '#/components/schemas/ExposureId'
      responses:
        '200':
          description: URI of file if successfully found
          content:
            application/json:
              schema: 
                type: string
          
        '404':
          description: Not Found
  '/science/search':
    get:
      description: Search storage for files based on query parameters
      summary: Search storage
      tags:
      - Science Data Access Service
      operationId: locate files
      parameters:
        - $ref: '#/components/parameters/fileType'
        - $ref: '#/components/parameters/originalFilename'
        - $ref: '#/components/parameters/programId'
        - $ref: '#/components/parameters/obsId'
        - $ref: '#/components/parameters/observer'
        - $ref: '#/components/parameters/objectName'
        - $ref: '#/components/parameters/ra'
        - $ref: '#/components/parameters/dec'
        - $ref: '#/components/parameters/radius'
        - $ref: '#/components/parameters/startDate'
        - $ref: '#/components/parameters/startTime'
        - $ref: '#/components/parameters/endDate'
        - $ref: '#/components/parameters/endTime'
        - $ref: '#/components/parameters/instrument'
        - $ref: '#/components/parameters/channel'
        - $ref: '#/components/parameters/integrationTime'
        - $ref: '#/components/parameters/coadds'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/scale'
        - $ref: '#/components/parameters/spectralResolution'
        - $ref: '#/components/parameters/aoMode'
        - $ref: '#/components/parameters/outputFormat'
        
      responses: 
        '200':
          description: URIs of matching files.  Media type depends on `outputType parameter`
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/ScienceSearchResultItem'
            text/csv:
              schema:
                type: string
                example: "uri1, name1, exposureID1, data1, time1, ra1, dec1, instrument1, channel1, itime,1 coadds1, filter1, scale1, res1, aoMode1\nuri2, name2, exposureID2, data2, time2, ra2, dec2, instrument2, channel2, itime2, coadds2, filter2, scale2, res2, aoMode2"
            text/xml:
              schema:
                $ref: '#/components/schemas/VOTABLE'
                
            text/html:
              schema:
                type: string
                example: "<html>\n<h1>myFavouriteGalaxies</h1>\n<h2>Velocities and Distance estimations</h2>\n<TABLE name=\"results\">\n<TR>\n<TD>010.68</TD><TD>+41.27</TD><TD>N 224</TD><TD>-297</TD><TD>5</TD><TD href=\"http://someurl/somefile.fits\">Download</TD><TD>0.7</TD>\n</TR>\n<TR>\n<TD>287.43</TD><TD>-63.85</TD><TD>N 6744</TD><TD>839</TD><TD>6</TD><TD>10.4</TD>\n</TR>\n<TR>\n<TD>023.48</TD><TD>+30.66</TD><TD>N 598</TD><TD>-182</TD><TD>3</TD><TD>0.7</TD><TD href=\"http://someurl/somefile2.fits\">Download</TD>\n</TR>\n</TABLE></html>"
        '404':
          description: Not Found
