openapi: 3.0.0
info:
  version: '0.9.0'
  title: Detector Data Collection Service Endpoints
  description: >-
    The Detector Data Collection Service (DDCS) watches for new exposures written by data producers and moves them to the permanent store.
    This services provides a method for a subsystem to configure a new transfer area for writing science data, and a method to 
    obtain a path to a transfer area for a specified subsystem.

    Visit [TIO Website](http://www.tmt.org) for more information.

    Complete codebase is available on [Github](https://github.com/tmtsoftware/dms).

    Collection of routes listed on this page are HTTP endpoints exposed by TIO Common Software.
  x-logo:
    url: tmt.png
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

paths:
  '/transfer/{subsystem}': 
    get: 
      description: Obtain path for a instrument transfer area on the Summit Storage
      summary: Get transfer area path
      tags:
      - Detector Data Collection Service
      operationId: get transfer path
      parameters:
        - name: subsystem
          in: path
          required: true
          description: specify subsystem that will be using transfer area
          schema:
            $ref: '../shared.yml#/components/schemas/Subsystem'
      responses: 
        '201':
          description: path of transfer area
          content:
            application/json:
              schema: 
                type: string
                example: /data/transfer/iris/
        '400':
          description:
            "Bad Request. Arguments provided were not correct or were incomplete: with explanatory text provided."
    post:
      description: Create an instrument transfer area on the Summit Storage for a subsystem
      summary: Create transfer area
      tags:
        - Detector Data Collection Service
      operationId: create transfer area
      parameters:
        - name: subsystem
          in: path
          required: true
          description: specify subsystem that will be using transfer area
          schema:
            $ref: '../shared.yml#/components/schemas/Subsystem'
      responses:
        '201':
          description: path of transfer area
          content:
            application/json:
              schema:
                type: string
                example: /data/transfer/iris/
        '400':
          description:
            "Bad Request. Arguments provided were not correct or were incomplete: with explanatory text provided."
        '401':
          description:
            "Bad Request. The caller is not authorized for this operation."
