openapi: 3.0.3
info:
  title: IVOA Cone Search
  description:
    This specification defines a simple query protocol for retrieving records from a catalog of astronomical sources.
    The query describes sky position and an angular distance, defining a cone on the sky.
    <p>
    The response returns a list of astronomical sources from the catalog whose positions lie within the cone, formatted as a VOTable.

  version: 1.0.3
  contact:
    email: dal@ivoa.net
externalDocs:
  description: The IVOA Cone Service recommendation document dated February 22, 2008
  url: https://ivoa.net/documents/cover/ConeSearch-20080222.html
servers:
  - url: 'https://future_catalog_server/V1/cone'
    description: This is the server that provides catalog search services.

paths:
  /:
    get:
      summary: Submit a Cone-Search query on the catalog database.
      tags:
        - ConeSearch
      parameters:
        - name: RA
          in: query
          example: 100.587
          required: true
          description:
            A right-ascension in the ICRS coordinate system for the position of the center of the cone to search, given in decimal degrees.
          schema:
            type: number
            format: float
        - name: DEC
          in: query
          example: -30.45
          required: true
          description:
            A declination in the ICRS coordinate system for the position of the center of the cone to search, given in decimal degrees.
          schema:
            type: number
            format: float
        - name: SR
          in: query
          example: 0.0125
          required: true
          description:
            The radius of the cone to search, given in decimal degrees.
          schema:
            type: number
            format: float
        - name: VERB
          in: query
          example: 2
          required: false
          schema:
            type: integer
            format: int32
        - name: MAXREC
          in: query
          example: 2001
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '../eng-shared/eng-shared.yaml#/components/schemas/VOTABLE'
